/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BudgetPlanDto {
  id?: string;
  initialIncome?: number;
  month?: number;
  year?: number;
}
