/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetPlanDto } from '../models/budget-plan-dto';
export interface BudgetChartDataDto {
  budgetPlan?: BudgetPlanDto;
  expectedTransactions?: Array<number>;
  realTransactions?: Array<number>;
}
