/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategorySummaryDto } from '../models/category-summary-dto';
export interface DashboardResponseDto {
  expensesByCategory?: Array<CategorySummaryDto>;
  totalExpenses?: number;
  totalIncome?: number;
}
