/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BudgetPlanDto } from '../models/budget-plan-dto';
export interface PageResponseBudgetPlanDto {
  content?: Array<BudgetPlanDto>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
