/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseTransactionDto } from '../../models/page-response-transaction-dto';

export interface FindAllTransactionsByBudget$Params {
  budgetId: string;
  page?: number;
  size?: number;
}

export function findAllTransactionsByBudget(http: HttpClient, rootUrl: string, params: FindAllTransactionsByBudget$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTransactionDto>> {
  const rb = new RequestBuilder(rootUrl, findAllTransactionsByBudget.PATH, 'get');
  if (params) {
    rb.path('budgetId', params.budgetId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseTransactionDto>;
    })
  );
}

findAllTransactionsByBudget.PATH = '/api/v1/transaction/budget/{budgetId}';
