/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BudgetPlanDto } from '../../models/budget-plan-dto';

export interface FindBudgetPlanById$Params {
  id: string;
}

export function findBudgetPlanById(http: HttpClient, rootUrl: string, params: FindBudgetPlanById$Params, context?: HttpContext): Observable<StrictHttpResponse<BudgetPlanDto>> {
  const rb = new RequestBuilder(rootUrl, findBudgetPlanById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BudgetPlanDto>;
    })
  );
}

findBudgetPlanById.PATH = '/api/v1/budget/{id}';
