/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseBudgetPlanDto } from '../../models/page-response-budget-plan-dto';

export interface FindAllBudgets$Params {
  page?: number;
  size?: number;
}

export function findAllBudgets(http: HttpClient, rootUrl: string, params?: FindAllBudgets$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBudgetPlanDto>> {
  const rb = new RequestBuilder(rootUrl, findAllBudgets.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseBudgetPlanDto>;
    })
  );
}

findAllBudgets.PATH = '/api/v1/budget/';
