/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardResponseDto } from '../../models/dashboard-response-dto';

export interface GetDashboard$Params {
  budgetId?: string;
}

export function getDashboard(http: HttpClient, rootUrl: string, params?: GetDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getDashboard.PATH, 'get');
  if (params) {
    rb.query('budgetId', params.budgetId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardResponseDto>;
    })
  );
}

getDashboard.PATH = '/api/v1/dashboard/';
